extends Node

# Reference book text
const reference_book_page_zero_title: String = "Welcome!"
const reference_book_page_zero_text: String = "'We were all fish once' - Old Gregg \nIf you can't tell a Cheese from a Fog Nose, you don't belong in the waters. This book contains everything you need to know about fish. More importantly, this book describes how to identify the 'good' fish from the 'bad' fish. If something doesn't look right with you catch, dispose of it as soon as possible. If you're reading this AFTER eating a bad fish, run as far away from civilization as you can..... Enjoy!"

const reference_book_page_one_title: String = "Plaice"
const reference_book_page_one_fish_texture: String = "res://resources/images/fish/fish_Plaice_Normal.png"
const reference_book_page_one_desc: String = "The most harmless of all fish. \nCan do no wrong. \nA bit boring though."
const reference_book_page_one_weight: String = "350g - 450g"
const reference_book_page_one_parasites: String = "None"
const reference_book_page_one_aura: String = "fishy"
const reference_book_page_one_value: String = "Low"
const reference_book_page_one_rarity: String = "Common"
const reference_book_page_one_glow: String = "Should not glow"

const reference_book_page_two_title: String = "Cheese"
const reference_book_page_two_fish_texture: String = "res://resources/images/fish/fish_cheese_normal.png"
const reference_book_page_two_desc: String = "You’ll know it from the smell. \nPairs well with a nice wine. \nDon’t leave it at room temp if you value your nose."
const reference_book_page_two_weight: String = "20g"
const reference_book_page_two_parasites: String = "None"
const reference_book_page_two_aura: String = "Stinky"
const reference_book_page_two_value: String = "Low"
const reference_book_page_two_rarity: String = "Common"
const reference_book_page_two_glow: String = "Should not glow"

const reference_book_page_three_title: String = "Fog Nose"
const reference_book_page_three_fish_texture: String = "res://resources/images/fish/fish_fog_nose_normal.png"
const reference_book_page_three_desc: String = "Easy to spot from the red glowing nose. Very delicate flesh. Thin as paper! \nThe nose is not edible, despite looking delicious."
const reference_book_page_three_weight: String = "1g - 7g"
const reference_book_page_three_parasites: String = "None"
const reference_book_page_three_aura: String = "Hauntingly Cute"
const reference_book_page_three_value: String = "Medium"
const reference_book_page_three_rarity: String = "Rare"
const reference_book_page_three_glow: String = "Should glow"

const reference_book_page_four_title: String = "Bi-Imp"
const reference_book_page_four_fish_texture: String = "res://resources/images/fish/fish_bi_imp_normal.png"
const reference_book_page_four_desc: String = "Two heads aren't always better than one. \nA lot of work to prepare. Worth it though. \nTwice the head. Twice the flavour."
const reference_book_page_four_weight: String = "44g - 60g"
const reference_book_page_four_parasites: String = "None"
const reference_book_page_four_aura: String = "Indecisive"
const reference_book_page_four_value: String = "High"
const reference_book_page_four_rarity: String = "Medium"
const reference_book_page_four_glow: String = "Should not glow"

const reference_book_page_five_title: String = "Lank"
const reference_book_page_five_fish_texture: String = "res://resources/images/fish/fish_lank_normal.png"
const reference_book_page_five_desc: String = "Longer than you'd think. Much longer. \nCould eat you whole, if you didn't move for 3 days. \nOne ate my ring. Took me a week to find it. Don't recommend."
const reference_book_page_five_weight: String = "4kg - 30kg"
const reference_book_page_five_parasites: String = "Yes (Adds flavour)"
const reference_book_page_five_aura: String = "Intense"
const reference_book_page_five_value: String = "Medium"
const reference_book_page_five_rarity: String = "Common"
const reference_book_page_five_glow: String = "Should not glow"
